# -*- coding: utf-8 -*-
"""correlacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgWeg3pverqL49TEvjbiK5NJ4t12tSKU
"""

pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("libreria").getOrCreate()

spark

data_var = [(3,4),(2,4),(3,4),(2,4),(5,4),(3,2),(4,3),(5,4),(4,4),(5,4),(3,4),(5,4),(3,4),(2,4),(4,4)]
columns_var = ["var1", "var2"]
variable_corr = spark.createDataFrame(data_var, columns_var)

correlacion = variable_corr.select(corr(col("var1"),col("var2")).alias("correlacion")).collect()[0]["correlacion"]

print("la correlacion es:",correlacion)