# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgWeg3pverqL49TEvjbiK5NJ4t12tSKU
"""

pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("libreria").getOrCreate()

spark

data= [("tijera",40),("cuadernos ",50), ("regla",30),("goma ",20), ("borrador",25),("lapiz ",35), ("tajador",15),("plumon ",45),]
colums = ["producto","cantidad"]
variable = spark.createDataFrame(data=data,schema=colums)

var_mediana=variable.approxQuantile("cantidad",[0.5],0.0)

print("la mediana es :",var_mediana)